### ISSUE TITLE
Permanently lost pawns on recovering stashed vehicles

### ISSUE THREAD

**Issue by ZzZombo** [SmashPhil/RimShips#280]
**Describe the bug**
When recovering stashed vehicles all pawns in the caravan are lost w/o a trace.

**To Reproduce**
I attached the save file where this happens as there are no relevant logs.

* Switch to the world view.
* Select either of the two caravans visiting the friendly settlement (you'd need to wait for a quest to finish to move the bigger, non-vehicle caravan).
* Order it to recover the stashed vehicles on the same tile.

**Additional context**
This problem also used to happen in the past so I ended up not using the feature. But this time I had not choice as the quest doesn't work with vehicle caravans and I needed as many of my colonists as possible to do it.

[v1.6 — Space Sentinels#§#Autosave-2.rws.zip](https://github.com/user-attachments/files/22868820/v1.6.Space.Sentinels.Autosave-2.rws.zip)

**Comment by SmashPhil** [comment]
Please attach your logs as well.

**Comment by SmashPhil** [comment]
As for it happening in the past, it was fixed in 1.6.2091
https://github.com/SmashPhil/Vehicle-Framework/commit/1a9a0ee10c147f9dec644b456806ded633e806dd

**Comment by ZzZombo** [comment]
As you wish: https://gist.github.com/ZzZombo/1b657230a8a44c5e1428934815747156. However, the linked commit seems to deal with a different case. In my save, even if I attempt to recover with the smaller, two people caravan, they still get lost forever.

**Comment by SmashPhil** [comment]
Right, I just meant the previous issue you may have been encountering.  There were 2 bugfixes for recovering stashed vehicles in the past.

Any other details about the recovery? Such as which vehicle you were recovering, the amount of people in the caravan, etc.

**Comment by ZzZombo** [comment]
The caravan originally had two wagons, one tango and one marshal. IIRC I split one wagon up from the rest, then ordered the bigger party to stash vehicles, then ordered them to fulfill the quest at the settlement. There were 9 colonists and an ally with them. The wagon had one colonist and the ally.

**Comment by SmashPhil** [comment]
I'm not able to reproduce this.  Do you have an additional video or list of steps to reproduce it reliably? Are you able to reproduce it or was this a 1 time thing?
